export default {
  tableName: "ODV_SITE_MASTER",
  dataKey: "SITE_ID,PLAN_VERSION",
  viewType: "crud",
  columnSetting: `PLAN_VERSION;버전,
    SITE_ID;사이트,
    CREATE_TIME:datetime;생성일,
    CREATE_USER,
    UPDATE_TIME:datetime;수정일,
    UPDATE_USER`,
  useMngProperty: true,
  hideVersion: true,
  isReadOnly: false,
  // columnSetting: [
  //   {
  //     key: "PLAN_VERSION",
  //     name: "PLAN_VERSION",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "MODULE_KEY",
  //     name: "MODULE_KEY",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "MODULE_KEY",
  //     name: "MODULE_KEY",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "SO_ID",
  //     name: "SO_ID",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "MO_ID",
  //     name: "MO_ID",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "LOT_ID",
  //     name: "LOT_ID",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "ITEM_ID",
  //     name: "ITEM_ID",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "IN_PLAN_QTY",
  //     name: "IN_PLAN_QTY",
  //     width: 0,
  //     type: "number",
  //     visible: true,
  //   },
  //   {
  //     key: "START_TIME",
  //     name: "START_TIME",
  //     width: 0,
  //     type: "datetime",
  //     visible: true,
  //   },
  //   {
  //     key: "END_TIME",
  //     name: "END_TIME",
  //     width: 0,
  //     type: "date",
  //     visible: true,
  //   },
  //   {
  //     key: "CREATE_TIME",
  //     name: "CREATE_TIME",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  //   {
  //     key: "UPDATE_USER",
  //     name: "UPDATE_USER",
  //     width: 0,
  //     type: "string",
  //     visible: true,
  //   },
  // ],
};
